// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporKulubu.Data;

#nullable disable

namespace SporKulubu.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260310145639_AidatSistemi")]
    partial class AidatSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SporKulubu.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ay")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OdendiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UyeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OdemeTarihi")
                        .HasDatabaseName("IX_Aidatlar_OdemeTarihi");

                    b.HasIndex("UyeId")
                        .HasDatabaseName("IX_Aidatlar_UyeId");

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Kontenjan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TakimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TakimId")
                        .HasDatabaseName("IX_Gruplar_TakimId");

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("SporKulubu.Models.SporSalonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SporSalonlari");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AntrenorAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId")
                        .HasDatabaseName("IX_Takimlar_SporSalonuId");

                    b.ToTable("Takimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AylikAidat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Branş")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Voleybol");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KiyafetNotlari")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("KiyafetVerildiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("KiyafetVerilisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonAidatOdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TakimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeliAdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeliTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdSoyad")
                        .HasDatabaseName("IX_Uyeler_AdSoyad");

                    b.HasIndex("GrupId")
                        .HasDatabaseName("IX_Uyeler_GrupId");

                    b.HasIndex("SporSalonuId")
                        .HasDatabaseName("IX_Uyeler_SporSalonuId");

                    b.HasIndex("TakimId")
                        .HasDatabaseName("IX_Uyeler_TakimId");

                    b.HasIndex("Telefon")
                        .HasDatabaseName("IX_Uyeler_Telefon");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("SporKulubu.Models.Aidat", b =>
                {
                    b.HasOne("SporKulubu.Models.Uye", "Uye")
                        .WithMany("Aidatlar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporKulubu.Models.Grup", b =>
                {
                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany("Gruplar")
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany("Takimlar")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.HasOne("SporKulubu.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany()
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grup");

                    b.Navigation("SporSalonu");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.SporSalonu", b =>
                {
                    b.Navigation("Takimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.Navigation("Gruplar");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.Navigation("Aidatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
