// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporKulubu.Data;

#nullable disable

namespace SporKulubu.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260309123216_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SporKulubu.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ay")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Kontenjan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TakimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TakimId");

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("SporKulubu.Models.SporSalonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SporSalonlari");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntrenorAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId");

                    b.ToTable("Takimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AylikAidat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branş")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KiyafetNotlari")
                        .HasColumnType("TEXT");

                    b.Property<bool>("KiyafetVerildiMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KiyafetVerilisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TakimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VeliAdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VeliTelefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.HasIndex("SporSalonuId");

                    b.HasIndex("TakimId");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("SporKulubu.Models.Aidat", b =>
                {
                    b.HasOne("SporKulubu.Models.Uye", "Uye")
                        .WithMany("Aidatlar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporKulubu.Models.Grup", b =>
                {
                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany("Gruplar")
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany("Takimlar")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.HasOne("SporKulubu.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany()
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Grup");

                    b.Navigation("SporSalonu");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.SporSalonu", b =>
                {
                    b.Navigation("Takimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.Navigation("Gruplar");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.Navigation("Aidatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
