// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SporKulubu.Data;

#nullable disable

namespace SporKulubu.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("SporKulubu.Models.Aidat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ay")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OdendiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UyeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OdemeTarihi")
                        .HasDatabaseName("IX_Aidatlar_OdemeTarihi");

                    b.HasIndex("UyeId")
                        .HasDatabaseName("IX_Aidatlar_UyeId");

                    b.ToTable("Aidatlar");
                });

            modelBuilder.Entity("SporKulubu.Models.AntrenmanProgrami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Baslangic")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Bitis")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TakimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupId");

                    b.HasIndex("TakimId");

                    b.ToTable("AntrenmanProgramlari");
                });

            modelBuilder.Entity("SporKulubu.Models.Antrenor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilResmi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uzmanlik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Antrenorler_Email");

                    b.ToTable("Antrenorler");
                });

            modelBuilder.Entity("SporKulubu.Models.AntrenorTakim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntrenorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtanmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TakimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AntrenorId")
                        .HasDatabaseName("IX_AntrenorTakimlar_AntrenorId");

                    b.HasIndex("GrupId");

                    b.HasIndex("SporSalonuId")
                        .HasDatabaseName("IX_AntrenorTakimlar_SporSalonuId");

                    b.HasIndex("TakimId");

                    b.ToTable("AntrenorTakimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Brans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("GrupVarMi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TakimVarMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SporSalonuId");

                    b.ToTable("Branslar");
                });

            modelBuilder.Entity("SporKulubu.Models.Grup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Kontenjan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TakimId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TakimId")
                        .HasDatabaseName("IX_Gruplar_TakimId");

                    b.ToTable("Gruplar");
                });

            modelBuilder.Entity("SporKulubu.Models.SporSalonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SporSalonlari");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AntrenorAdi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BransId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BransId")
                        .HasDatabaseName("IX_Takimlar_BransId");

                    b.HasIndex("SporSalonuId")
                        .HasDatabaseName("IX_Takimlar_SporSalonuId");

                    b.ToTable("Takimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AylikAidat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BransId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branş")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("KiyafetNotlari")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("KiyafetVerildiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("KiyafetVerilisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonAidatOdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SporSalonuId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TakimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeliAdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VeliTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdSoyad")
                        .HasDatabaseName("IX_Uyeler_AdSoyad");

                    b.HasIndex("BransId")
                        .HasDatabaseName("IX_Uyeler_BransId");

                    b.HasIndex("GrupId")
                        .HasDatabaseName("IX_Uyeler_GrupId");

                    b.HasIndex("SporSalonuId")
                        .HasDatabaseName("IX_Uyeler_SporSalonuId");

                    b.HasIndex("TakimId")
                        .HasDatabaseName("IX_Uyeler_TakimId");

                    b.HasIndex("Telefon")
                        .HasDatabaseName("IX_Uyeler_Telefon");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("SporKulubu.Models.Yoklama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntrenorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Not")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<int>("UyeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AntrenorId");

                    b.HasIndex("UyeId");

                    b.ToTable("Yoklamalar");
                });

            modelBuilder.Entity("SporKulubu.Models.Aidat", b =>
                {
                    b.HasOne("SporKulubu.Models.Uye", "Uye")
                        .WithMany("Aidatlar")
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporKulubu.Models.AntrenmanProgrami", b =>
                {
                    b.HasOne("SporKulubu.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grup");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.AntrenorTakim", b =>
                {
                    b.HasOne("SporKulubu.Models.Antrenor", "Antrenor")
                        .WithMany("AntrenorTakimlar")
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SporKulubu.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany()
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Antrenor");

                    b.Navigation("Grup");

                    b.Navigation("SporSalonu");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.Brans", b =>
                {
                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany()
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("SporKulubu.Models.Grup", b =>
                {
                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany("Gruplar")
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.HasOne("SporKulubu.Models.Brans", "Brans")
                        .WithMany()
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany("Takimlar")
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brans");

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.HasOne("SporKulubu.Models.Brans", "Brans")
                        .WithMany()
                        .HasForeignKey("BransId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.Grup", "Grup")
                        .WithMany()
                        .HasForeignKey("GrupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.SporSalonu", "SporSalonu")
                        .WithMany()
                        .HasForeignKey("SporSalonuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SporKulubu.Models.Takim", "Takim")
                        .WithMany()
                        .HasForeignKey("TakimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brans");

                    b.Navigation("Grup");

                    b.Navigation("SporSalonu");

                    b.Navigation("Takim");
                });

            modelBuilder.Entity("SporKulubu.Models.Yoklama", b =>
                {
                    b.HasOne("SporKulubu.Models.Antrenor", "Antrenor")
                        .WithMany()
                        .HasForeignKey("AntrenorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SporKulubu.Models.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("SporKulubu.Models.Antrenor", b =>
                {
                    b.Navigation("AntrenorTakimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.SporSalonu", b =>
                {
                    b.Navigation("Takimlar");
                });

            modelBuilder.Entity("SporKulubu.Models.Takim", b =>
                {
                    b.Navigation("Gruplar");
                });

            modelBuilder.Entity("SporKulubu.Models.Uye", b =>
                {
                    b.Navigation("Aidatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
